/**
 * Created by Edge on 6/15/2017.
 */

export const CONFIRM_USER_REQUEST = "XcelTrip/Register/CONFIRM_USER_REQUEST";
export const CONFIRM_USER_SUCCESS = "XcelTrip/Register/CONFIRM_USER_SUCCESS";
export const CONFIRM_USER_ERROR = "XcelTrip/Register/CONFIRM_USER_ERROR";
export const RESEND_CONFIRMATION_REQUEST = "XcelTrip/Register/RESEND_CONFIRMATION_REQUEST";
export const RESEND_CONFIRMATION_SUCCESS = "XcelTrip/Register/RESEND_CONFIRMATION_SUCCESS";
export const RESEND_CONFIRMATION_ERROR = "XcelTrip/Register/RESEND_CONFIRMATION_ERROR";
